### ISSUE TITLE
Determination of package version

### ISSUE THREAD

**Issue by panmau** [xoofx/dotnet-releaser#18]
I set up my repo similarly to grpc-curl. These are my configs.

<details>
<summary>fsproj</summary>

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>TubeDl</RootNamespace>
    <AssemblyName>switchtube-dl</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
  # Compile Includes
  </ItemGroup>

  <ItemGroup>
    <ResolvedFileToPublish Include="..\..\README.md">
        <RelativePath>README.md</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </ResolvedFileToPublish>

    <ResolvedFileToPublish Include="..\..\LICENSE">
        <RelativePath>LICENSE</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </ResolvedFileToPublish>

   # Package References removed
  </ItemGroup>

</Project>
```

</details>

<details>
<summary>pipeline</summary>

```
name: ci

on:
    push:
        paths-ignore:
            - 'CHANGELOG.md'
            - 'README.md'
    pull_request:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2

            - name: Install .NET 6.0 🧳
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '6.0.x'

            - name: Install dependencies 🔌
              run: dotnet restore src

            - name: Build project 🏗
              run: dotnet build src -c Release --no-restore

            - name: Publish 🚀
              if: github.event_name == 'push'
              run: |
                  if ( "${{github.ref}}" -match "^refs/tags/[0-9]+\.[0-9]+\.[0-9]+" ) {
                      dotnet tool install --global dotnet-releaser --version "0.1.*"
                      dotnet-releaser publish --github-token ${{secrets.TOKEN_GITHUB}} src/dotnet-releaser.toml
                  } else {
                      echo "publish is only enabled by tagging with a release tag"
                  }
```
</details>

<details>
<summary>toml file (in src folder)</summary>

```
# configuration file for dotnet-releaser
[msbuild]
project = "SwitchTubeDl/SwitchTubeDl.fsproj"
[github]
user = "panmau"
repo = "switchtube-dl"

[changelog]
path = "../CHANGELOG.md" # Default config didn't find Changelog

[nuget]
publish = false
```

</details>

What I didn't find out yet is how the version of the package is determined. I added tag 1.0.0 and it made the 1.0.0 version. Then i made 1.0.1 and it made another 1.0.0 version.

Shouldn't this be determined from the associated GitHub Tag? Or do I need to set the Version field in the fsproj? 

I didn't find anything about it in the User Guide and Readme.

Thanks a lot for your help.
Other than that I have to say that it's working really well!
