### ISSUE TITLE
"Unexpected error Repository creation failed" for Homebrew

### ISSUE THREAD

**Issue by panmau** [xoofx/dotnet-releaser#20]
With Homebrew publishing enabled I get the following error from dotnet-releaser:
```
...
info: dotnet-releaser[49]
      Creating Homebrew repository panmau/homebrew-panmau
Unexpected error Repository creation failed.
Error: Process completed with exit code 1.
```
Unfortunately the error output is not more detailed.

This is my toml file:
```toml
[msbuild]
project = "SwitchTubeDl/SwitchTubeDl.fsproj"
[github]
user = "panmau"
repo = "switchtube-dl"

[nuget]
publish = false

[brew]
home = "homebrew-panmau"
```
The access token has the following permissions:
![image](https://user-images.githubusercontent.com/16801528/153769681-c30169a0-ecff-4958-8d64-936cfcf0b847.png)

My repo is currently private as it's not quite ready for publication yet.

Is there any more information I can provide for easier inspection into what the exact error is?
