### ISSUE TITLE
run command producing different assemblies than build

### ISSUE THREAD

**Issue by phil-scott-78** [xoofx/dotnet-releaser#47]
I'm getting different assemblies when running on GH CI rather than locally with `dotnet releaser build`. It's a simple nuget package with one assembly, but `IsTrimmable` is set to true which I strongly suspect is at fault here. When I look at the assembly created in CI it contains no types. I've tried setting some msbuild.properties like so

``` toml
[msbuild.properties]
PublishTrimmed = false
PublishSingleFile = false
SelfContained = false
PublishReadyToRun = false 
```

but it doesn't seem to have any change on what is built in CI.

Project is here - https://github.com/phil-scott-78/Icons

Here are a couple of packages. 
* Created via `build` and uploaded manually - https://www.nuget.org/packages/BadIdeas.Icons.FontAwesome/0.0.0-alpha.0.14
* Created via `run` and pushed via CI - https://www.nuget.org/packages/BadIdeas.Icons.FontAwesome/0.0.0-alpha.0.13
