### ISSUE TITLE
how do we only do builds for win-x64

### ISSUE THREAD

**Issue by 3UR** [xoofx/dotnet-releaser#48]
instead of doing all this other stuff like nupkg linux etc how do i just build for win-x64?

**Comment by xoofx** [comment]
There is a doc that explains this around [here](https://github.com/xoofx/dotnet-releaser/tree/main/doc#27-packaging) (`custom` profile)

```toml
profile = "custom"
[msbuild]
project = "your-solution.sln"
[github]
user = "your_user_name"
repo = "your_repo"
[nuget]
publish = false
[[pack]]
rid = ["win-x64"]
kinds = ["zip"]
```
